#!/data/data/com.termux/files/usr/bin/bash
#
# Agency Agents (stop) — Termux:Widget entry (generated by install-widgets.sh).
# Stops the web server. Nothing else is touched (Termux, other servers).
#
set -u
if pkill -f "web/server\.mjs"; then
  echo "Agency Agents server stopped."
  # Release the wake lock we took on start (only if nothing else needs it).
  command -v termux-wake-unlock >/dev/null 2>&1 && termux-wake-unlock || true
else
  echo "Server not running."
fi
sleep 1
