#!/data/data/com.termux/files/usr/bin/bash
#
# Agency Agents — Termux:Widget entry (generated by install-widgets.sh).
#
# Starts the web server when it isn't running, waits for it to be healthy,
# then opens the app in the browser/PWA. Safe to tap repeatedly: a second
# start dies harmlessly (port in use) while the live server keeps serving.
#
set -u
APP_DIR="__APP_DIR__"
PORT="${AGENCY_PORT:-8788}"
URL="http://localhost:$PORT"

have_curl() { command -v curl >/dev/null 2>&1; }

healthy() { curl -sf --max-time 2 "$URL/api/health" >/dev/null 2>&1; }

if have_curl && healthy; then
  :
else
  # Detached start — the widget tap returns immediately, logs go to a file.
  (cd "$APP_DIR" && nohup node web/server.mjs --port "$PORT" > "$APP_DIR/web/server.log" 2>&1 &)
  if have_curl; then
    # Cold start on a phone takes a few seconds; wait before opening.
    i=0
    while [ "$i" -lt 30 ]; do
      healthy && break
      sleep 0.5
      i=$((i + 1))
    done
  else
    sleep 3
  fi
fi

# Open the app: Android's viewer first, termux-open-url as the fallback.
am start -a android.intent.action.VIEW -d "$URL" >/dev/null 2>&1 \
  || termux-open-url "$URL" >/dev/null 2>&1 || true
